import {
  LayoutDashboard, Inbox, Sun, CalendarClock, Calendar, ListChecks, FolderKanban, List, Tag, Flag, BarChart3, Timer, CheckCircle2, Trash2, Settings, Search,
  Plus, X, Check, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, MoreHorizontal, Clock, Repeat, Bell, BellOff, Paperclip, MapPin, Link2, AlignLeft, Circle, CircleDot,
  Folder, Briefcase, Home, BookOpen, Heart, GraduationCap, Code, Dumbbell, Plane, ShoppingCart, Palette, Users, Archive, ArchiveRestore, RotateCcw, Copy, Pencil, GripVertical,
  Filter, SlidersHorizontal, Command, Keyboard, Download, Upload, Play, Pause, Square, SkipForward, AlertTriangle, AlertCircle, Info, WifiOff, Wifi, RefreshCw, Menu,
  CalendarDays, CalendarRange, CalendarCheck, ArrowRight, ArrowUpRight, Hash, Layers, Star, Eye, EyeOff, LogOut, Sparkles, Target, TrendingUp, Zap, Bookmark, BookmarkPlus, CircleSlash, FileText, Smartphone, Monitor, HardDrive, ShieldCheck, Trash, ExternalLink, CalendarPlus, ListTodo, CheckSquare, MinusSquare, Square as SquareIcon, Undo2, Maximize2, Minimize2, PanelLeft, PanelLeftClose, XCircle, Hourglass, CircleCheck, CircleX, Moon, Coffee,
} from 'lucide-react'

const ICONS = {
  'layout-dashboard': LayoutDashboard,
  inbox: Inbox,
  sun: Sun,
  'calendar-clock': CalendarClock,
  calendar: Calendar,
  'list-checks': ListChecks,
  'folder-kanban': FolderKanban,
  list: List,
  tag: Tag,
  flag: Flag,
  'bar-chart-3': BarChart3,
  timer: Timer,
  'check-circle-2': CheckCircle2,
  'trash-2': Trash2,
  settings: Settings,
  search: Search,
  plus: Plus,
  x: X,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'more-horizontal': MoreHorizontal,
  clock: Clock,
  repeat: Repeat,
  bell: Bell,
  'bell-off': BellOff,
  paperclip: Paperclip,
  'map-pin': MapPin,
  link: Link2,
  'align-left': AlignLeft,
  circle: Circle,
  'circle-dot': CircleDot,
  folder: Folder,
  briefcase: Briefcase,
  home: Home,
  'book-open': BookOpen,
  heart: Heart,
  'graduation-cap': GraduationCap,
  code: Code,
  dumbbell: Dumbbell,
  plane: Plane,
  'shopping-cart': ShoppingCart,
  palette: Palette,
  users: Users,
  archive: Archive,
  'archive-restore': ArchiveRestore,
  'rotate-ccw': RotateCcw,
  copy: Copy,
  pencil: Pencil,
  'grip-vertical': GripVertical,
  filter: Filter,
  sliders: SlidersHorizontal,
  command: Command,
  keyboard: Keyboard,
  download: Download,
  upload: Upload,
  play: Play,
  pause: Pause,
  stop: Square,
  'skip-forward': SkipForward,
  'alert-triangle': AlertTriangle,
  'alert-circle': AlertCircle,
  info: Info,
  'wifi-off': WifiOff,
  wifi: Wifi,
  refresh: RefreshCw,
  menu: Menu,
  'calendar-days': CalendarDays,
  'calendar-range': CalendarRange,
  'calendar-check': CalendarCheck,
  'calendar-plus': CalendarPlus,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  hash: Hash,
  layers: Layers,
  star: Star,
  eye: Eye,
  'eye-off': EyeOff,
  'log-out': LogOut,
  sparkles: Sparkles,
  target: Target,
  'trending-up': TrendingUp,
  zap: Zap,
  bookmark: Bookmark,
  'bookmark-plus': BookmarkPlus,
  'circle-slash': CircleSlash,
  'file-text': FileText,
  smartphone: Smartphone,
  monitor: Monitor,
  'hard-drive': HardDrive,
  'shield-check': ShieldCheck,
  trash: Trash,
  'external-link': ExternalLink,
  'list-todo': ListTodo,
  'check-square': CheckSquare,
  'minus-square': MinusSquare,
  square: SquareIcon,
  undo: Undo2,
  maximize: Maximize2,
  minimize: Minimize2,
  'panel-left': PanelLeft,
  'panel-left-close': PanelLeftClose,
  'x-circle': XCircle,
  hourglass: Hourglass,
  'circle-check': CircleCheck,
  'circle-x': CircleX,
  moon: Moon,
  coffee: Coffee,
}

export function Icon({ name, size = 18, className, strokeWidth = 1.75, ...rest }) {
  const Component = ICONS[name] || Circle
  return <Component size={size} strokeWidth={strokeWidth} className={className} aria-hidden="true" focusable="false" {...rest} />
}

export const ICON_NAMES = Object.keys(ICONS)
